/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellTasksRouteImport } from './routes/_shell.tasks'
import { Route as ShellSignsRouteImport } from './routes/_shell.signs'
import { Route as ShellQualityRouteImport } from './routes/_shell.quality'
import { Route as ShellProgressRouteImport } from './routes/_shell.progress'
import { Route as ShellPortalRouteImport } from './routes/_shell.portal'
import { Route as ShellMapRouteImport } from './routes/_shell.map'
import { Route as ShellIntegrationsRouteImport } from './routes/_shell.integrations'
import { Route as ShellIncidentsRouteImport } from './routes/_shell.incidents'
import { Route as ShellExecutiveRouteImport } from './routes/_shell.executive'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellApiRouteImport } from './routes/_shell.api'
import { Route as ShellAiRouteImport } from './routes/_shell.ai'
import { Route as ShellSignsIndexRouteImport } from './routes/_shell.signs.index'
import { Route as ShellSignsRegistryRouteImport } from './routes/_shell.signs.registry'
import { Route as ShellSignsNewRouteImport } from './routes/_shell.signs.new'
import { Route as ShellSignsIdRouteImport } from './routes/_shell.signs.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSignsRoute = ShellSignsRouteImport.update({
  id: '/signs',
  path: '/signs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellQualityRoute = ShellQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProgressRoute = ShellProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPortalRoute = ShellPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMapRoute = ShellMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsRoute = ShellIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIncidentsRoute = ShellIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExecutiveRoute = ShellExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApiRoute = ShellApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAiRoute = ShellAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSignsIndexRoute = ShellSignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSignsRoute,
} as any)
const ShellSignsRegistryRoute = ShellSignsRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => ShellSignsRoute,
} as any)
const ShellSignsNewRoute = ShellSignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShellSignsRoute,
} as any)
const ShellSignsIdRoute = ShellSignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellSignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof ShellAiRoute
  '/api': typeof ShellApiRoute
  '/dashboard': typeof ShellDashboardRoute
  '/executive': typeof ShellExecutiveRoute
  '/incidents': typeof ShellIncidentsRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/map': typeof ShellMapRoute
  '/portal': typeof ShellPortalRoute
  '/progress': typeof ShellProgressRoute
  '/quality': typeof ShellQualityRoute
  '/signs': typeof ShellSignsRouteWithChildren
  '/tasks': typeof ShellTasksRoute
  '/signs/$id': typeof ShellSignsIdRoute
  '/signs/new': typeof ShellSignsNewRoute
  '/signs/registry': typeof ShellSignsRegistryRoute
  '/signs/': typeof ShellSignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof ShellAiRoute
  '/api': typeof ShellApiRoute
  '/dashboard': typeof ShellDashboardRoute
  '/executive': typeof ShellExecutiveRoute
  '/incidents': typeof ShellIncidentsRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/map': typeof ShellMapRoute
  '/portal': typeof ShellPortalRoute
  '/progress': typeof ShellProgressRoute
  '/quality': typeof ShellQualityRoute
  '/tasks': typeof ShellTasksRoute
  '/signs/$id': typeof ShellSignsIdRoute
  '/signs/new': typeof ShellSignsNewRoute
  '/signs/registry': typeof ShellSignsRegistryRoute
  '/signs': typeof ShellSignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/ai': typeof ShellAiRoute
  '/_shell/api': typeof ShellApiRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/executive': typeof ShellExecutiveRoute
  '/_shell/incidents': typeof ShellIncidentsRoute
  '/_shell/integrations': typeof ShellIntegrationsRoute
  '/_shell/map': typeof ShellMapRoute
  '/_shell/portal': typeof ShellPortalRoute
  '/_shell/progress': typeof ShellProgressRoute
  '/_shell/quality': typeof ShellQualityRoute
  '/_shell/signs': typeof ShellSignsRouteWithChildren
  '/_shell/tasks': typeof ShellTasksRoute
  '/_shell/signs/$id': typeof ShellSignsIdRoute
  '/_shell/signs/new': typeof ShellSignsNewRoute
  '/_shell/signs/registry': typeof ShellSignsRegistryRoute
  '/_shell/signs/': typeof ShellSignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai'
    | '/api'
    | '/dashboard'
    | '/executive'
    | '/incidents'
    | '/integrations'
    | '/map'
    | '/portal'
    | '/progress'
    | '/quality'
    | '/signs'
    | '/tasks'
    | '/signs/$id'
    | '/signs/new'
    | '/signs/registry'
    | '/signs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai'
    | '/api'
    | '/dashboard'
    | '/executive'
    | '/incidents'
    | '/integrations'
    | '/map'
    | '/portal'
    | '/progress'
    | '/quality'
    | '/tasks'
    | '/signs/$id'
    | '/signs/new'
    | '/signs/registry'
    | '/signs'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/ai'
    | '/_shell/api'
    | '/_shell/dashboard'
    | '/_shell/executive'
    | '/_shell/incidents'
    | '/_shell/integrations'
    | '/_shell/map'
    | '/_shell/portal'
    | '/_shell/progress'
    | '/_shell/quality'
    | '/_shell/signs'
    | '/_shell/tasks'
    | '/_shell/signs/$id'
    | '/_shell/signs/new'
    | '/_shell/signs/registry'
    | '/_shell/signs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/signs': {
      id: '/_shell/signs'
      path: '/signs'
      fullPath: '/signs'
      preLoaderRoute: typeof ShellSignsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/quality': {
      id: '/_shell/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof ShellQualityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/progress': {
      id: '/_shell/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ShellProgressRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/portal': {
      id: '/_shell/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof ShellPortalRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/map': {
      id: '/_shell/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof ShellMapRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations': {
      id: '/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ShellIntegrationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/incidents': {
      id: '/_shell/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof ShellIncidentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/executive': {
      id: '/_shell/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ShellExecutiveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/api': {
      id: '/_shell/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ShellApiRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ai': {
      id: '/_shell/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof ShellAiRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/signs/': {
      id: '/_shell/signs/'
      path: '/'
      fullPath: '/signs/'
      preLoaderRoute: typeof ShellSignsIndexRouteImport
      parentRoute: typeof ShellSignsRoute
    }
    '/_shell/signs/registry': {
      id: '/_shell/signs/registry'
      path: '/registry'
      fullPath: '/signs/registry'
      preLoaderRoute: typeof ShellSignsRegistryRouteImport
      parentRoute: typeof ShellSignsRoute
    }
    '/_shell/signs/new': {
      id: '/_shell/signs/new'
      path: '/new'
      fullPath: '/signs/new'
      preLoaderRoute: typeof ShellSignsNewRouteImport
      parentRoute: typeof ShellSignsRoute
    }
    '/_shell/signs/$id': {
      id: '/_shell/signs/$id'
      path: '/$id'
      fullPath: '/signs/$id'
      preLoaderRoute: typeof ShellSignsIdRouteImport
      parentRoute: typeof ShellSignsRoute
    }
  }
}

interface ShellSignsRouteChildren {
  ShellSignsIdRoute: typeof ShellSignsIdRoute
  ShellSignsNewRoute: typeof ShellSignsNewRoute
  ShellSignsRegistryRoute: typeof ShellSignsRegistryRoute
  ShellSignsIndexRoute: typeof ShellSignsIndexRoute
}

const ShellSignsRouteChildren: ShellSignsRouteChildren = {
  ShellSignsIdRoute: ShellSignsIdRoute,
  ShellSignsNewRoute: ShellSignsNewRoute,
  ShellSignsRegistryRoute: ShellSignsRegistryRoute,
  ShellSignsIndexRoute: ShellSignsIndexRoute,
}

const ShellSignsRouteWithChildren = ShellSignsRoute._addFileChildren(
  ShellSignsRouteChildren,
)

interface ShellRouteChildren {
  ShellAiRoute: typeof ShellAiRoute
  ShellApiRoute: typeof ShellApiRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellExecutiveRoute: typeof ShellExecutiveRoute
  ShellIncidentsRoute: typeof ShellIncidentsRoute
  ShellIntegrationsRoute: typeof ShellIntegrationsRoute
  ShellMapRoute: typeof ShellMapRoute
  ShellPortalRoute: typeof ShellPortalRoute
  ShellProgressRoute: typeof ShellProgressRoute
  ShellQualityRoute: typeof ShellQualityRoute
  ShellSignsRoute: typeof ShellSignsRouteWithChildren
  ShellTasksRoute: typeof ShellTasksRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAiRoute: ShellAiRoute,
  ShellApiRoute: ShellApiRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellExecutiveRoute: ShellExecutiveRoute,
  ShellIncidentsRoute: ShellIncidentsRoute,
  ShellIntegrationsRoute: ShellIntegrationsRoute,
  ShellMapRoute: ShellMapRoute,
  ShellPortalRoute: ShellPortalRoute,
  ShellProgressRoute: ShellProgressRoute,
  ShellQualityRoute: ShellQualityRoute,
  ShellSignsRoute: ShellSignsRouteWithChildren,
  ShellTasksRoute: ShellTasksRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
